# Generated by Django 4.0.3 on 2022-04-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial', models.CharField(max_length=200, verbose_name='Testimoio(s)')),
                ('testimonial_msg', models.TextField(blank=True, null=True, verbose_name='Mensaje (opcional)')),
                ('testimonial_msg_english', models.TextField(blank=True, null=True, verbose_name='Message (optional)')),
                ('video', models.FileField(upload_to='testimonials', verbose_name='Vídeo')),
                ('active', models.CharField(choices=[('0', 'Activo'), ('1', 'Inactivo'), ('2', 'Descontinuado')], default='0', max_length=1, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['active', '-created'],
            },
        ),
    ]
