# Generated by Django 4.0.3 on 2022-04-03 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Categoría')),
                ('name_english', models.CharField(blank=True, max_length=250, null=True, verbose_name='Categoría')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Clasificación',
                'verbose_name_plural': 'Clasificaciones',
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveField(
            model_name='service',
            name='classifications',
        ),
        migrations.DeleteModel(
            name='Classification',
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.category', verbose_name='Categoria'),
            preserve_default=False,
        ),
    ]
