# Generated by Django 4.0.3 on 2022-04-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_category_remove_service_classifications_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_english',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_english',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Service'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('name', 'category')},
        ),
    ]
