# Generated by Django 4.0.3 on 2022-04-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Texto inicio')),
                ('model', models.CharField(choices=[('image-red', 'Componente imagen rojo'), ('image-green', 'Componente imagen verde'), ('image-green-two', 'Componente imagen verde claro'), ('mosaic', 'Mosaico')], default='image-red', max_length=30, verbose_name='Modelo texto inicio')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('description_english', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image_one', models.URLField(max_length=255, verbose_name='Imagen')),
                ('image_two', models.URLField(blank=True, max_length=255, null=True, verbose_name='Imagen (solo para mosaico)')),
                ('url', models.URLField(blank=True, max_length=250, null=True, verbose_name='Enlace del texto')),
                ('order', models.SmallIntegerField(default=1, verbose_name='Orden')),
                ('active', models.CharField(choices=[('0', 'Activo'), ('1', 'Inactivo'), ('2', 'Descontinuado')], default='0', max_length=1, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Texto inicio',
                'verbose_name_plural': 'Textos inicio',
                'ordering': ['active', 'order', 'name'],
            },
        ),
    ]
