# Generated by Django 4.0.3 on 2022-04-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_hometext_image_one_alter_hometext_image_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometext',
            name='url',
            field=models.URLField(default='www.google.com', max_length=250, verbose_name='Enlace del texto'),
            preserve_default=False,
        ),
    ]
