# Generated by Django 4.0.3 on 2022-04-03 00:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_name', models.CharField(max_length=200, verbose_name='Nombre del texto')),
                ('text_name_english', models.CharField(blank=True, max_length=200, null=True, verbose_name='Text name')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Texto')),
                ('text_english', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texto')),
                ('video', models.FileField(blank=True, null=True, upload_to='us', verbose_name='Vídeo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='us', verbose_name='Imagen')),
                ('order', models.SmallIntegerField(default=1, verbose_name='Orden')),
                ('active', models.CharField(choices=[('0', 'Activo'), ('1', 'Inactivo'), ('2', 'Descontinuado')], default='0', max_length=1, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Texto (nosotros)',
                'verbose_name_plural': 'Textos (nosotros)',
                'ordering': ['active', 'order', 'text_name'],
            },
        ),
    ]
