# Generated by Django 4.0.3 on 2022-04-03 00:01

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200, verbose_name='Cargo')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team', verbose_name='Foto (opcional)')),
                ('bio', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Biografía')),
                ('bio_english', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Biography')),
                ('active', models.CharField(choices=[('0', 'Activo'), ('1', 'Inactivo'), ('2', 'Descontinuado')], default='0', max_length=1, verbose_name='Estado')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Integrante')),
            ],
            options={
                'verbose_name': 'Integrante',
                'verbose_name_plural': 'Integrantes',
                'ordering': ['active', 'member'],
            },
        ),
    ]
