# Generated by Django 4.0.3 on 2022-04-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberteam',
            name='position_english',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Position'),
        ),
    ]
